# Generated by Django 5.2 on 2025-04-22 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Location', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='response_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
